We downloaded data from https://www.kaggle.com/burak3ergun/loan-data-set/version/1.

In [1]:
import pandas as pd;
from sklearn.model_selection import train_test_split;
from sklearn.preprocessing import OneHotEncoder;
import numpy as np;
from sklearn.ensemble import RandomForestClassifier;
from sklearn.model_selection import GridSearchCV;
from sklearn.linear_model import LogisticRegression;

###Import all data from the csv


In [2]:
df = pd.read_csv("loan_data_set.csv");
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

###Get rid of all rows that have missing data

In [3]:
data = df.dropna()  
data

Loan_ID  Gender Married Dependents     Education Self_Employed  \
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
5               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[480 rows x 13 columns]

In [4]:
data.drop(data.columns[[0, -4]], axis=1, inplace= True);
X = data.iloc[:, :-1];
y = data.iloc[:, -1];

C:\Users\siwei\.virtualenvs\Final_Project-7ACreyYE\lib\site-packages\pandas\core\frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [5]:
print(X)
print(y)

     Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
5      Male     Yes          2      Graduate           Yes             5417   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Credit_History 

###Split data into three sets (training, validation, test)

###Preprocessing data and let all features to have numbered value

In [6]:
y[y=='Y'] = 1;
y[y=='N'] = 0;
y = y.to_numpy();
y=y.astype('int');
y

C:\Users\siwei\.virtualenvs\Final_Project-7ACreyYE\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\siwei\.virtualenvs\Final_Project-7ACreyYE\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,

In [7]:
X_encode = X[['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area']];
X_quant = X[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Credit_History']];
X_quant = X_quant.to_numpy();

enc = OneHotEncoder(handle_unknown='ignore', sparse= False)
X_encode = enc.fit_transform(X_encode)
X_ = np.c_[X_encode, X_quant]
X_

array([[0.000e+00, 1.000e+00, 0.000e+00, ..., 1.508e+03, 1.280e+02,
        1.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 6.600e+01,
        1.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 2.358e+03, 1.200e+02,
        1.000e+00],
       ...,
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 2.400e+02, 2.530e+02,
        1.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 1.870e+02,
        1.000e+00],
       [1.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 1.330e+02,
        0.000e+00]])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X_, y, test_size= 0.30, random_state= 42);
X_test, X_validation, y_test, y_validation = train_test_split(X_test, y_test, test_size= 0.50, random_state = 42);
print(X_train);
print(X_test);
print(X_validation);
print(type(y_train));

[[0.000e+00 1.000e+00 0.000e+00 ... 2.420e+02 1.080e+02 1.000e+00]
 [0.000e+00 1.000e+00 1.000e+00 ... 0.000e+00 1.130e+02 1.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 ... 4.486e+03 1.000e+02 1.000e+00]
 ...
 [0.000e+00 1.000e+00 0.000e+00 ... 1.210e+03 1.300e+02 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 2.669e+03 1.620e+02 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 3.500e+03 8.800e+01 1.000e+00]]
[[0.000e+00 1.000e+00 0.000e+00 ... 0.000e+00 6.000e+01 0.000e+00]
 [0.000e+00 1.000e+00 1.000e+00 ... 0.000e+00 6.500e+01 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 2.859e+03 1.440e+02 1.000e+00]
 ...
 [0.000e+00 1.000e+00 1.000e+00 ... 0.000e+00 8.000e+01 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 2.925e+03 1.130e+02 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 7.250e+03 1.800e+02 0.000e+00]]
[[0.000e+00 1.000e+00 1.000e+00 ... 1.987e+03 1.110e+02 0.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 2.100e+03 3.040e+02 1.000e+00]
 [0.000e+00 1.000e+00 1.000e+00 ... 3.750e+03 1.87

###Train using Random Forest

In [9]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train));
print(clf.score(X_test, y_test));

0.8125
0.7361111111111112


###Further optimize hyperparameters choice

In [10]:
parameters = {'n_estimators':(128, 256, 512, 1024), 'criterion':('gini', 'entropy'), 'max_depth': (3, 4, 5, 6), 'class_weight':(None, 'balanced', 'balanced_subsample')}
clf_ = GridSearchCV(clf, parameters, scoring= f1_weighted);
clf_.fit(np.r_[X_train, X_validation], np.r_[y_train, y_validation]);

NameError: name 'f1_weighted' is not defined

In [11]:
print(clf_.best_params_)

NameError: name 'clf_' is not defined

###Train the model using better params

In [12]:
clf_op = RandomForestClassifier(max_depth=3, random_state=0, n_estimators=256)
clf_op.fit(X_train, y_train)
print(clf_op.score(X_train, y_train));
print(clf_op.score(X_test, y_test));

0.8154761904761905
0.7638888888888888


###Use Linear Regression

In [13]:
clf_lr = LogisticRegression(random_state=0,max_iter = 200).fit(X_train, y_train);
print(clf_lr.score(X_train, y_train))
print(clf_lr.score(X_validation, y_validation))
print(clf_lr.score(X_test, y_test))

0.8125
0.8333333333333334
0.7638888888888888
