We downloaded data from https://www.kaggle.com/burak3ergun/loan-data-set/version/1.

In [125]:
import pandas as pd;
from sklearn.model_selection import train_test_split;
from sklearn.preprocessing import OneHotEncoder;
import numpy as np;
from sklearn.ensemble import RandomForestClassifier;
from sklearn.model_selection import GridSearchCV;
from sklearn.linear_model import LogisticRegression;

###Import all data from the csv


In [102]:
df = pd.read_csv("/content/loan_data_set.csv");
df

Loan_ID  Gender Married  ... Credit_History Property_Area Loan_Status
0    LP001002    Male      No  ...            1.0         Urban           Y
1    LP001003    Male     Yes  ...            1.0         Rural           N
2    LP001005    Male     Yes  ...            1.0         Urban           Y
3    LP001006    Male     Yes  ...            1.0         Urban           Y
4    LP001008    Male      No  ...            1.0         Urban           Y
..        ...     ...     ...  ...            ...           ...         ...
609  LP002978  Female      No  ...            1.0         Rural           Y
610  LP002979    Male     Yes  ...            1.0         Rural           Y
611  LP002983    Male     Yes  ...            1.0         Urban           Y
612  LP002984    Male     Yes  ...            1.0         Urban           Y
613  LP002990  Female      No  ...            0.0     Semiurban           N

[614 rows x 13 columns]

###Get rid of all rows that have missing data

In [103]:
data = df.dropna()  
data

Loan_ID  Gender Married  ... Credit_History Property_Area Loan_Status
1    LP001003    Male     Yes  ...            1.0         Rural           N
2    LP001005    Male     Yes  ...            1.0         Urban           Y
3    LP001006    Male     Yes  ...            1.0         Urban           Y
4    LP001008    Male      No  ...            1.0         Urban           Y
5    LP001011    Male     Yes  ...            1.0         Urban           Y
..        ...     ...     ...  ...            ...           ...         ...
609  LP002978  Female      No  ...            1.0         Rural           Y
610  LP002979    Male     Yes  ...            1.0         Rural           Y
611  LP002983    Male     Yes  ...            1.0         Urban           Y
612  LP002984    Male     Yes  ...            1.0         Urban           Y
613  LP002990  Female      No  ...            0.0     Semiurban           N

[480 rows x 13 columns]

In [104]:
data.drop(data.columns[[0, -4]], axis=1, inplace= True);
X = data.iloc[:, :-1];
y = data.iloc[:, -1];

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [105]:
print(X)
print(y)

     Gender Married Dependents  ... LoanAmount Credit_History  Property_Area
1      Male     Yes          1  ...      128.0            1.0          Rural
2      Male     Yes          0  ...       66.0            1.0          Urban
3      Male     Yes          0  ...      120.0            1.0          Urban
4      Male      No          0  ...      141.0            1.0          Urban
5      Male     Yes          2  ...      267.0            1.0          Urban
..      ...     ...        ...  ...        ...            ...            ...
609  Female      No          0  ...       71.0            1.0          Rural
610    Male     Yes         3+  ...       40.0            1.0          Rural
611    Male     Yes          1  ...      253.0            1.0          Urban
612    Male     Yes          2  ...      187.0            1.0          Urban
613  Female      No          0  ...      133.0            0.0      Semiurban

[480 rows x 10 columns]
1      N
2      Y
3      Y
4      Y
5      Y
      

###Split data into three sets (training, validation, test)

###Preprocessing data and let all features to have numbered value

In [106]:
y[y=='Y'] = 1;
y[y=='N'] = 0;
y = y.to_numpy();
y=y.astype('int');
y

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,

In [107]:
X_encode = X[['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area']];
X_quant = X[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Credit_History']];
X_quant = X_quant.to_numpy();

enc = OneHotEncoder(handle_unknown='ignore', sparse= False)
X_encode = enc.fit_transform(X_encode)
X_ = np.c_[X_encode, X_quant]
X_

array([[0.000e+00, 1.000e+00, 0.000e+00, ..., 1.508e+03, 1.280e+02,
        1.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 6.600e+01,
        1.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 2.358e+03, 1.200e+02,
        1.000e+00],
       ...,
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 2.400e+02, 2.530e+02,
        1.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 1.870e+02,
        1.000e+00],
       [1.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 1.330e+02,
        0.000e+00]])

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X_, y, test_size= 0.30, random_state= 42);
X_test, X_validation, y_test, y_validation = train_test_split(X_test, y_test, test_size= 0.50, random_state = 42);
print(X_train);
print(X_test);
print(X_validation);
print(type(y_train));

[[0.000e+00 1.000e+00 0.000e+00 ... 2.420e+02 1.080e+02 1.000e+00]
 [0.000e+00 1.000e+00 1.000e+00 ... 0.000e+00 1.130e+02 1.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 ... 4.486e+03 1.000e+02 1.000e+00]
 ...
 [0.000e+00 1.000e+00 0.000e+00 ... 1.210e+03 1.300e+02 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 2.669e+03 1.620e+02 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 3.500e+03 8.800e+01 1.000e+00]]
[[0.000e+00 1.000e+00 0.000e+00 ... 0.000e+00 6.000e+01 0.000e+00]
 [0.000e+00 1.000e+00 1.000e+00 ... 0.000e+00 6.500e+01 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 2.859e+03 1.440e+02 1.000e+00]
 ...
 [0.000e+00 1.000e+00 1.000e+00 ... 0.000e+00 8.000e+01 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 2.925e+03 1.130e+02 1.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 7.250e+03 1.800e+02 0.000e+00]]
[[0.000e+00 1.000e+00 1.000e+00 ... 1.987e+03 1.110e+02 0.000e+00]
 [0.000e+00 1.000e+00 0.000e+00 ... 2.100e+03 3.040e+02 1.000e+00]
 [0.000e+00 1.000e+00 1.000e+00 ... 3.750e+03 1.87

###Train using Random Forest

In [131]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train));
print(clf.score(X_test, y_test));

0.8125
0.7361111111111112


###Further optimize hyperparameters choice

In [121]:
parameters = {'n_estimators':(128, 256, 512, 1024), 'criterion':('gini', 'entropy'), 'max_depth': (3, 4, 5, 6), 'class_weight':(None, 'balanced', 'balanced_subsample')}
clf_ = GridSearchCV(clf, parameters, scoring= f1_weighted);
clf_.fit(np.r_[X_train, X_validation], np.r_[y_train, y_validation]);

In [124]:
print(clf_.best_params_)

{'class_weight': None, 'criterion': 'gini', 'max_depth': 3, 'n_estimators': 256}


###Train the model using better params

In [130]:
clf_op = RandomForestClassifier(max_depth=3, random_state=0, n_estimators=256)
clf_op.fit(X_train, y_train)
print(clf_op.score(X_train, y_train));
print(clf_op.score(X_test, y_test));

0.8154761904761905
0.7638888888888888


###Use Linear Regression

In [128]:
clf_lr = LogisticRegression(random_state=0).fit(X_train, y_train);
clf_lr.score(X_validation, y_validation)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.8333333333333334